#!/usr/bin/env python3
"""
compile-lists.py — Merge community.txt and scraped-raw.txt into a JSON filter list.

Sources:
  sources/community.txt    — hand-curated entries (all AdGuard plaintext directives)
  sources/scraped-raw.txt  — auto-generated by scraper.py; contains SECTION markers
                             that route servers to the correct target lists

Routing:
  child-safe, family-safe  — hard-blocked scraped servers + all community entries
  teen                     — teen-flagged scraped servers + all community entries

Usage:
    python scripts/compile-lists.py --target child-safe
    python scripts/compile-lists.py --target family-safe
    python scripts/compile-lists.py --target teen
"""

import json
import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT   = Path(__file__).parent.parent
SOURCES_DIR = REPO_ROOT / "sources"
LISTS_DIR   = REPO_ROOT / "lists"

COMMUNITY_FILE = SOURCES_DIR / "community.txt"
SCRAPED_FILE   = SOURCES_DIR / "scraped-raw.txt"

TARGET_DESCRIPTIONS = {
    "child-safe": (
        "Strict child-safe filter list. Blocks all NSFW, adult, and age-inappropriate "
        "Discord servers, channels, and keywords."
    ),
    "family-safe": (
        "Family-safe filter list. Blocks explicit adult content and overtly harmful servers "
        "while permitting general teen/young adult communities."
    ),
    "teen": (
        "Teen filter list (13-17). Blocks explicitly pornographic, illegal, and harmful content "
        "while permitting general mature discussion, gaming communities, and age-appropriate social spaces."
    ),
}

# channel patterns and keywords excluded from the teen profile
TEEN_EXCLUDED_CATEGORIES = {"mature", "suggestive", "horny", "feet", "fetish", "kink", "thirst"}
TEEN_EXCLUDED_KEYWORDS = {
    "sex", "cock", "dick", "pussy", "boobs", "tits", "ass", "cum",
    "masturbat", "orgasm", "handjob", "dildo", "vibrator",
}

COMMUNITY_ENTRY_RE = re.compile(r"^\|\|(?P<type>server|category|keyword):(?P<value>[^\s!]+)")
SCRAPED_SERVER_RE  = re.compile(r"^\|\|server:(\d{17,19})")


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_community(path: Path) -> dict[str, set[str]]:
    """
    Parse sources/community.txt — standard AdGuard plaintext format.
    Returns {"servers": set, "categories": set, "keywords": set}.
    """
    entries: dict[str, set[str]] = {
        "servers": set(), "categories": set(), "keywords": set(),
    }

    if not path.exists():
        print(f"[compiler] WARNING: community file not found, skipping: {path}", file=sys.stderr)
        return entries

    for lineno, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("!"):
            continue

        m = COMMUNITY_ENTRY_RE.match(line)
        if not m:
            continue

        etype = m.group("type")
        value = m.group("value").strip()

        if etype == "server":
            entries["servers"].add(value)
        elif etype == "category":
            entries["categories"].add(value)
        elif etype == "keyword":
            entries["keywords"].add(value)

    print(
        f"[compiler] community: {len(entries['servers'])} servers, "
        f"{len(entries['categories'])} categories, {len(entries['keywords'])} keywords"
    )
    return entries


def parse_scraped(path: Path) -> dict[str, set[str]]:
    """
    Parse sources/scraped-raw.txt between ! BEGIN SCRAPED and ! END SCRAPED.
    Tracks SECTION markers to separate hard-blocked from teen-flagged servers.

    Returns {"hard-blocked": set[server_ids], "teen-flagged": set[server_ids]}.
    """
    sections: dict[str, set[str]] = {"hard-blocked": set(), "teen-flagged": set()}

    if not path.exists():
        print(f"[compiler] WARNING: scraped file not found, skipping: {path}", file=sys.stderr)
        return sections

    content = path.read_text(encoding="utf-8")
    begin_pos = content.find("! BEGIN SCRAPED")
    end_pos   = content.find("! END SCRAPED")

    if begin_pos == -1 or end_pos == -1:
        print(f"[compiler] WARNING: no BEGIN/END SCRAPED markers in {path.name} — no scraped servers loaded", file=sys.stderr)
        return sections

    block = content[begin_pos: end_pos + len("! END SCRAPED")]
    current_section = "hard-blocked"

    for line in block.splitlines():
        line = line.strip()
        if "SECTION hard-blocked" in line:
            current_section = "hard-blocked"
            continue
        if "SECTION teen-flagged" in line:
            current_section = "teen-flagged"
            continue

        m = SCRAPED_SERVER_RE.match(line)
        if m:
            sections[current_section].add(m.group(1))

    print(
        f"[compiler] scraped: {len(sections['hard-blocked'])} hard-blocked servers, "
        f"{len(sections['teen-flagged'])} teen-flagged servers"
    )
    return sections


# ---------------------------------------------------------------------------
# Merge + filter
# ---------------------------------------------------------------------------

def select_scraped_servers(scraped: dict[str, set[str]], target: str) -> set[str]:
    """Return the scraped server set appropriate for the given target."""
    if target in ("child-safe", "family-safe"):
        return set(scraped["hard-blocked"])
    if target == "teen":
        return set(scraped["teen-flagged"])
    return set()


def apply_target_filter(
    entries: dict[str, set[str]], target: str
) -> dict[str, set[str]]:
    """Remove category/keyword entries that don't apply to the target profile."""
    if target == "teen":
        entries["categories"] = entries["categories"] - TEEN_EXCLUDED_CATEGORIES
        entries["keywords"]   = entries["keywords"]   - TEEN_EXCLUDED_KEYWORDS
    return entries


# ---------------------------------------------------------------------------
# Version management
# ---------------------------------------------------------------------------

def bump_patch_version(output_path: Path) -> str:
    """
    Read the existing JSON file and increment the patch segment of its version.
    Returns "1.0.0" if the file doesn't exist or the version can't be parsed.
    """
    if not output_path.exists():
        return "1.0.0"
    try:
        existing = json.loads(output_path.read_text(encoding="utf-8"))
        parts = existing.get("version", "1.0.0").split(".")
        if len(parts) == 3:
            return f"{parts[0]}.{parts[1]}.{int(parts[2]) + 1}"
    except Exception as exc:
        print(f"[compiler] WARNING: could not parse existing version in {output_path.name}: {exc}", file=sys.stderr)
    return "1.0.0"


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def build_json(
    servers: set[str],
    categories: set[str],
    keywords: set[str],
    target: str,
    version: str,
) -> dict:
    return {
        "version": version,
        "updated": date.today().isoformat(),
        "description": TARGET_DESCRIPTIONS.get(target, f"{target} filter list."),
        "blocked_servers":          sorted(servers),
        "blocked_channel_patterns": sorted(categories),
        "blocked_keywords":         sorted(keywords),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compile plaintext filter sources into a JSON filter list."
    )
    parser.add_argument(
        "--target",
        required=True,
        choices=list(TARGET_DESCRIPTIONS.keys()),
        help="Which filter list to generate.",
    )
    args = parser.parse_args()
    target = args.target

    # Parse sources
    community = parse_community(COMMUNITY_FILE)
    scraped   = parse_scraped(SCRAPED_FILE)

    # Combine servers: target-appropriate scraped set + all community servers
    servers    = select_scraped_servers(scraped, target) | community["servers"]
    categories = set(community["categories"])
    keywords   = set(community["keywords"])

    # Apply profile-specific exclusions to categories/keywords
    filtered = apply_target_filter(
        {"servers": servers, "categories": categories, "keywords": keywords},
        target,
    )

    # Bump version from existing file
    output_path = LISTS_DIR / f"{target}.json"
    version = bump_patch_version(output_path)

    # Build and write output
    output = build_json(
        filtered["servers"],
        filtered["categories"],
        filtered["keywords"],
        target,
        version,
    )
    LISTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")

    # Summary line
    print(
        f"Compiled {output_path.name}: "
        f"{len(filtered['servers'])} servers, "
        f"{len(filtered['categories'])} channel patterns, "
        f"{len(filtered['keywords'])} keywords  "
        f"(version {version})"
    )


if __name__ == "__main__":
    main()
